config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :operators, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :operators
  resources :templates
  resources :orders
  resources :clients
  resources :constructors
  get 'template/create'

  get 'template/new'

  get 'template/create'

  get 'template/update'

  get 'template/edit'

  get 'template/destroy'

  get 'template/index'

  get 'template/show'

end

app/models/constructor.rb
class Constructor < ActiveRecord::Base
	has_many :templates
end

app/controllers/constructors_controller.rb
class ConstructorsController < ApplicationController
  before_action :set_constructor, only: [:show, :edit, :update, :destroy]

  # GET /constructors
  # GET /constructors.json
  def index
    @constructors = Constructor.all
  end

  # GET /constructors/1
  # GET /constructors/1.json
  def show
  end

  # GET /constructors/new
  def new
    @constructor = Constructor.new
  end

  # GET /constructors/1/edit
  def edit
  end

  # POST /constructors
  # POST /constructors.json
  def create
    @constructor = Constructor.new(constructor_params)

    respond_to do |format|
      if @constructor.save
        format.html { redirect_to @constructor, notice: 'Constructor was successfully created.' }
        format.json { render :show, status: :created, location: @constructor }
      else
        format.html { render :new }
        format.json { render json: @constructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /constructors/1
  # PATCH/PUT /constructors/1.json
  def update
    respond_to do |format|
      if @constructor.update(constructor_params)
        format.html { redirect_to @constructor, notice: 'Constructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @constructor }
      else
        format.html { render :edit }
        format.json { render json: @constructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /constructors/1
  # DELETE /constructors/1.json
  def destroy
    @constructor.destroy
    respond_to do |format|
      format.html { redirect_to constructors_url, notice: 'Constructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_constructor
      @constructor = Constructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def constructor_params
      params.require(:constructor).permit(:name, :content)
    end
end

app/helpers/constructors_helper.rb
module ConstructorsHelper
end

app/views/constructors/_form.html.erb
<%= form_for(@constructor) do |f| %>
  <% if @constructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@constructor.errors.count, "error") %> prohibited this constructor from being saved:</h2>

      <ul>
      <% @constructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/constructors/edit.html.erb
<h1>Editing Constructor</h1>

<%= render 'form' %>

<%= link_to 'Show', @constructor %> |
<%= link_to 'Back', constructors_path %>

app/views/constructors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Constructors</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @constructors.each do |constructor| %>
      <tr>
        <td><%= link_to 'Show', constructor %></td>
        <td><%= link_to 'Edit', edit_constructor_path(constructor) %></td>
        <td><%= link_to 'Destroy', constructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Constructor', new_constructor_path %>

app/views/constructors/new.html.erb
<h1>New Constructor</h1>

<%= render 'form' %>

<%= link_to 'Back', constructors_path %>

app/views/constructors/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_constructor_path(@constructor) %> |
<%= link_to 'Back', constructors_path %>